export enum SubscriptionType {
  MONTHLY_COMMITMENT = 'MONTHLY_COMMITMENT',
  QUARTERLY_COMMITMENT = 'QUARTERLY_COMMITMENT',
  MONTHLY_UPFRONT = 'MONTHLY_UPFRONT',
  QUARTERLY_UPFRONT = 'QUARTERLY_UPFRONT',
}
